conditions:
  IFR: red
  INOP: '#050505'
  INVALID: pink
  LIFR: magenta
  MVFR: blue
  NIGHT: yellow
  NIGHT_DARK: '#141400'
  SMOKE: '#323232'
  VFR: green
metar_refresh_interval: 15
sunrise_refresh_interval: 1080
metar_invalid_age : 90
metar_inop_age: 180
night_lights: true
pixel_map:
  '0': KEYW
  '1': KMTH
  '2': KHST
  '3': KMIA
  '4': KFLL
  '5': KFXE
  '6': KBCT
  '7': KPBI
  '8': KSUA
  '9': KOBE
  '10': KFPR
  '11': KVRB
  '12': KMLB
  '13': KXMR
  '14': KTIX
  '15': KMCO
  '16': KEVB
  '17': KDAB
  '18': KOMN
  '19': KVQQ
  '20': KNIP
  '21': KCRG
  '22': KNRB
  '23': KFHB
  '24': KJAX
  '25': KSGJ
  '26': KJAX
  '27': KLCQ
  '28': K24J
  '29': K40J
  '30': KTLH
  '31': K1J0
  '32': K54J
  '33': KPNS
  '34': KDTS
  '35': KECP
  '36': KPAM
  '37': KPBI
  '38': KCTY
  '39': KGNV
  '40': KX60
  '41': KOCF
  '42': KLEE
  '43': KINF
  '44': KCGC
  '45': KBKV
  '46': KTPA
  '47': KSRQ
  '48': KRSW
  '49': KIMM
  '50': KAPF
  '51': KHST
  '52': KTMB
  '53': KMIA
  '54': KOPF
  '55': KHWO
  '56': KFLL
  '57': KFXE
  '58': KPMP
  '59': KBCT
  '60': KSFB
  '61': KORL
  '62': KMCO
  '63': KISM
  '64': KZPH
  '65': KVDF
  '66': KTPA
  '67': KCLW
  '68': KPIE
  '69': KTPF
  '70': KMCE
  '71': KSPG
  '72': KSRQ
pixelcount: 73
setup_complete: true
renderer_config:
  hostname: 10.20.219.92
  name: remote
  port: 5001
