conditions:
  IFR: red
  INOP: '#050505'
  INVALID: pink
  LIFR: magenta
  MVFR: blue
  NIGHT: yellow
  NIGHT_DARK: '#141400'
  SMOKE: '#323232'
  VFR: green
metar_refresh_interval: 15
sunrise_refresh_interval: 1080
metar_invalid_age : 90
metar_inop_age: 180
night_lights: true
pixelcount: 73
setup_complete: false
renderer_config:
  hostname: 10.20.219.92
  name: remote
  port: 5001
